# TransformerLM
model:
  vocab_size: 32000
  context_length: 512
  num_layers: 12
  d_model: 768
  num_heads: 12
  d_ff: 2048  # should be 8/3 * d_model
  rms_norm_eps: 1.0e-5
  use_causal: True
  use_rope: True
  theta: 10000.0

# Optimizer
optimizer:
  name: adamw  # adamw | sgd
  adamw:
    lr: 1.0e-3
    betas: [0.9, 0.95]
    eps: 1.0e-8
    weight_decay: 0.1
  sgd:
    lr: 0.1

data:  # vocab_size must match. TinyStories = 10000, owt = 32000
  train_path: /dev/shm/owt_train.npy
  val_path: /dev/shm/owt_train.npy
  batch_size: 128

train:
  num_steps: 8000
  max_l2_norm: 1.0
  seed: 42
  resume: null  # null = from scratch, str = path to a checkpoint

  lr_schedule:
    t_warmup: 250
    t_c: null  # null = num_steps
    lr_min_ratio: 0.05

  run_dir: ./runs
  run_name: full_owt_run  # null = timestamp or --set overrides, str = runs/<str>.
  log_every: 50
  eval_every: 500
  eval_batches: 20
  ckpt_every: 2000
  keep_last: 1 # number of checkpoints to save. null = all.

runtime:
  device: cuda  # cpu | mps | cuda | cuda:id
  dtype: bfloat16  # float32 | bfloat16
