# TransformerLM
model:
  vocab_size: 32000
  context_length: 1024
  num_layers: 12
  d_model: 768
  num_heads: 12
  d_ff: 2048
  rms_norm_eps: 1.0e-5
  use_causal: True
  use_rope: True
  theta: 10000.0

# Optimizer
optimizer:
  name: adamw  # adamw | sgd
  adamw:
    lr: 6.0e-4
    betas: [0.9, 0.95]
    eps: 1.0e-8
    weight_decay: 0.01
  sgd:
    lr: 0.1

data:
  path: ./data/train_data.npy
  batch_size: 32

train:
  num_steps: 10
  max_l2_norm: 1.0
  seed: 42

  lr_schedule:
    t_warmup: 800
    t_c: null  # null = num_steps
    lr_min_ratio: 0.1

  run_dir: ./runs
  run_name: null  # null = timestamp, str = runs/<str>.
  log_every: 1
  ckpt_every: 2000
  keep_last: 3 # number of checkpoints to save. null = all.

runtime:
  device: mps  # cpu | mps | cuda | cuda:id
  dtype: float32  # float32 | float16 | bfloat16
