# TransformerLM
model:
  vocab_size: 10000
  context_length: 256
  num_layers: 4
  d_model: 512
  num_heads: 16
  d_ff: 1344  # should be 8/3 * d_model
  rms_norm_eps: 1.0e-5
  use_causal: True
  use_rope: True
  theta: 10000.0

# Optimizer
optimizer:
  name: adamw  # adamw | sgd
  adamw:
    lr: 6.0e-4
    betas: [0.9, 0.95]
    eps: 1.0e-8
    weight_decay: 0.01
  sgd:
    lr: 0.1

data:  # vocab_size must match. TinyStories = 10000, owt = 32000
  train_path: ./tokenized/tinystories_train.npy
  val_path: ./tokenized/tinystories_valid.npy
  batch_size: 32

train:
  num_steps: 2000
  max_l2_norm: 1.0
  seed: 42
  resume: null  # null = from scratch, str = path to a checkpoint

  lr_schedule:
    t_warmup: 400
    t_c: null  # null = num_steps
    lr_min_ratio: 0.1

  run_dir: ./runs
  run_name: null  # null = timestamp or --set overrides, str = runs/<str>.
  log_every: 20
  eval_every: 100
  eval_batches: 20
  ckpt_every: 1000
  keep_last: 3 # number of checkpoints to save. null = all.

runtime:
  device: mps  # cpu | mps | cuda | cuda:id
  dtype: float32  # float32 | bfloat16
